version: "3"

services:
  notebook:
    build : ./
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - type: bind
        source: ./
        target: /work
